version: "2.1"
services:
  boots:
    image: quay.io/tinkerbell/boots:latest
    restart: unless-stopped
    network_mode: host
    command: -dhcp-addr 0.0.0.0:67 -tftp-addr $TINKERBELL_HOST_IP:69 -http-addr $TINKERBELL_HOST_IP:80 -log-level DEBUG
    environment:
      API_AUTH_TOKEN: ${PACKET_API_AUTH_TOKEN:-ignored}
      API_CONSUMER_TOKEN: ${PACKET_CONSUMER_TOKEN:-ignored}
      FACILITY_CODE: ${FACILITY:-onprem}
      PACKET_ENV: ${PACKET_ENV:-testing}
      PACKET_VERSION: ${PACKET_VERSION:-ignored}
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN:-ignored}
      ROLLBAR_DISABLE: ${ROLLBAR_DISABLE:-1}
      MIRROR_HOST: ${TINKERBELL_NGINX_IP:-127.0.0.1}
      DNS_SERVERS: 8.8.8.8
      PUBLIC_IP: $TINKERBELL_HOST_IP
      BOOTP_BIND: $TINKERBELL_HOST_IP:67
      HTTP_BIND: $TINKERBELL_HOST_IP:80
      SYSLOG_BIND: $TINKERBELL_HOST_IP:514
      TFTP_BIND: $TINKERBELL_HOST_IP:69
      DOCKER_REGISTRY: $TINK_IP
      REGISTRY_USERNAME: $TINKERBELL_REGISTRY_USERNAME
      REGISTRY_PASSWORD: $TINKERBELL_REGISTRY_PASSWORD
      TINKERBELL_GRPC_AUTHORITY: $TINK_IP:$TINK_GRPC_PORT
      TINKERBELL_CERT_URL: http://$TINK_IP:$TINK_HTTP_PORT/cert
      ELASTIC_SEARCH_URL: $TINKERBELL_HOST_IP:9200
      DATA_MODEL_VERSION: 1
    depends_on:
      db:
        condition: service_healthy
    ports:
      - $TINKERBELL_HOST_IP:80:80/tcp
      - 67:67/udp
      - 69:69/udp

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - ${TINKERBELL_NGINX_IP:-127.0.0.1}:80:80/tcp
    volumes:
      - ./state/webroot:/usr/share/nginx/html/
