version: "2.1"
services:
  boots:
    image: quay.io/tinkerbell/boots:latest
    restart: unless-stopped
    network_mode: host
    command: -dhcp-addr 0.0.0.0:67 -tftp-addr 0.0.0.0:69 -http-addr 0.0.0.0:80 -log-level DEBUG
    environment:
      API_AUTH_TOKEN: ${PACKET_API_AUTH_TOKEN:-ignored}
      API_CONSUMER_TOKEN: ${PACKET_CONSUMER_TOKEN:-ignored}
      FACILITY_CODE: ${FACILITY:-onprem}
      PACKET_ENV: ${PACKET_ENV:-testing}
      PACKET_VERSION: ${PACKET_VERSION:-ignored}
      ROLLBAR_TOKEN: ${ROLLBAR_TOKEN:-ignored}
      ROLLBAR_DISABLE: ${ROLLBAR_DISABLE:-1}
      MIRROR_BASE_URL: http://$TINK_IP:$TINK_MIRROR_PORT
      DNS_SERVERS: 8.8.8.8
      DOCKER_REGISTRY: $TINK_IP:$TINK_REGISTRY_PORT
      REGISTRY_USERNAME: $TINK_REGISTRY_USERNAME
      REGISTRY_PASSWORD: $TINK_REGISTRY_PASSWORD
      TINKERBELL_GRPC_AUTHORITY: $TINK_IP:$TINK_GRPC_PORT
      TINKERBELL_CERT_URL: http://$TINK_IP:$TINK_HTTP_PORT/cert
      DATA_MODEL_VERSION: 1
    ports:
      - 80:80/tcp
      - 67:67/udp
      - 69:69/udp
