apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: worker
spec:
  terminationGracePeriodSeconds: 30
  domain:
    clock:
      utc: {}
      timer:
        hpet:
          present: false
        pit:
          tickPolicy: delay
        rtc:
          tickPolicy: catchup
    resources:
      requests:
        memory: 1024M
    devices:
      #autoattachGraphicsDevice: false
      disks:
      - name: emptydisk
        disk:
          bus: virtio
        bootOrder: 2
      interfaces:
      - name: default
        masquerade: {}
      - name: tink-dev
        bridge: {}
        macAddress: "08:00:27:00:00:01"
        bootOrder: 1
  networks:
  - name: default
    pod: {}
  - name: tink-dev
    multus:
      networkName: tink-dev-no-ip
  volumes:
  - name: emptydisk
    emptyDisk:
      capacity: "10Gi"
