apiVersion: cert-manager.io/v1beta1
kind: Certificate
metadata:
  name: tink-server-certificate
spec:
  secretName: tink-server-certificate
  dnsNames:
  - tink-server
  - tink-server.default
  - tink-server.default.svc
  - tink-server.default.svc.cluster.local
  issuerRef:
    name: selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tink-server
spec:
  selector:
    matchLabels:
      app: tink-server
  template:
    metadata:
      labels:
        app: tink-server
    spec:
      containers:
      - name: tink-server
        image: quay.io/tinkerbell/tink:latest
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 42113
          name: grpc-authority
          protocol: TCP
        - containerPort: 42114
          name: http-authority
          protocol: TCP
        volumeMounts:
        - mountPath: /certs
          name: tink-server-certificate
          readOnly: true
        livenessProbe:
          failureThreshold: 30
          httpGet:
            path: /cert
            port: http-authority
            scheme: HTTP
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 2
        args:
        - --facility=onprem
        - --ca-cert=/certs/ca.crt
        - --tls-cert=/certs/tls.crt
        - --tls-key=/certs/tls.key
        env:
        - name: PACKET_ENV
          value: testing
        - name: PACKET_VERSION
          value: ignored
        - name: PGDATABASE
          value: tinkerbell
        - name: PGHOST
          value: db-postgresql
        - name: PGPASSWORD
          valueFrom:
            secretKeyRef:
              name: db-postgresql
              key: postgresql-password
        - name: PGPORT
          value: "5432"
        - name: PGSSLMODE
          value: disable
        - name: PGUSER
          value: tinkerbell
        - name: ROLLBAR_DISABLE
          value: "1"
        - name: ROLLBAR_TOKEN
          value: ignored
        - name: TINKERBELL_GRPC_AUTHORITY
          value: :42113
        - name: TINKERBELL_HTTP_AUTHORITY
          value: :42114
        - name: TINK_AUTH_PASSWORD
          valueFrom:
            secretKeyRef:
              name: tink-credentials
              key: TINKERBELL_TINK_PASSWORD
        - name: TINK_AUTH_USERNAME
          valueFrom:
            secretKeyRef:
              name: tink-credentials
              key: TINKERBELL_TINK_USERNAME
      volumes:
      - name: tink-server-certificate
        secret:
          secretName: tink-server-certificate
---
apiVersion: v1
kind: Service
metadata:
  name: tink-server
spec:
  ports:
  - name: grpc-authority
    port: 42113
    targetPort: grpc-authority
  - name: http-authority
    port: 42114
    targetPort: http-authority
  selector:
    app: tink-server
---
apiVersion: v1
kind: Service
metadata:
  name: tink-server-node
spec:
  type: NodePort
  selector:
    app: tink-server
  ports:
  - name: grpc-authority
    port: 42113
    targetPort: grpc-authority
  - name: http-authority
    port: 42114
    targetPort: http-authority
